### ISSUE TITLE
UPPERCASE and lowersace on group not working?

### ISSUE THREAD

**Issue by Puliczek** [stephen-riley/regexworkbench#7]
How to get it works?

Regex:
`ID_OSOB_([A-Z_a-złóźżćęą]+)`

Replace
`ID_OSOB_${\U1}(""),` - not working
`ID_OSOB_${\u1}(""),` - not working
`ID_OSOB_$\U{1}(""),` - not working
`ID_OSOB_\U${1}(""),` - not working
`ID_OSOB_${1:\U}(""),` - not working
`ID_OSOB_${1:+\U}(""),` - not working

Search Text:
**ID_OSOB_Bułgaria**

Replaced Text **SHOULD BE**:
**ID_OSOB_BUŁGARIA(""),**

However replaced Text is
**NULL (invalid regular expression)**
or
**ID_OSOB_Bułgaria(""),**

**Comment by stephen-riley** [comment]
Ah, good catch, thank you!  I was not using the `PCRE2_SUBSTITUTE_EXTENDED` option when calling `pcre2_substitute()`.  I will fix this in [pcre2-wasm](https://github.com/stephen-riley/pcre2-wasm) and update this project.

**Comment by stephen-riley** [comment]
Okay, fixed in 2.0.4, published to the Marketplace.  Please update to latest version.

The syntax you'll want to use is `ID_OSOB_\U${1}(""),`, as shown in the attached picture.

![image](https://user-images.githubusercontent.com/8561865/74618023-e43a1a00-50e4-11ea-9afb-ba89b7f77f0a.png)

Thanks for using the extension!
